### ISSUE TITLE
Maximum height is limited to 10 pages

### ISSUE THREAD

**Issue by alexgarciab** [burnnat/custom-page-size#2]
Maximum height is limited to 10 pages. It is necessary not to have this limitation for larger documents.

**Comment by burnnat** [comment]
Hi @alexgarciab, I'm not entirely sure what you mean or how to reproduce. I tried creating a blank document with 20 pages and was able to set a custom height. Do you get an error message? And is there anything else special about your document that could potentially be contributing, other than the page count?

**Comment by burnnat** [comment]
Sorry @alexgarciab I see now what you're saying - I missed the fact that you were talking about the maximum height, not the maximum document length. The maximum height/width limitation was requested by Google to comply with their policies on addon input validation. The maximum value is set to 10 feet in either dimension, which was chosen because it is larger than the maximum pages sizes for both Microsoft Word (22 inches) and OpenOffice/LibreOffice (3 meters). I'm not opposed to raising the limit, but I'd like to know more about your use case for extremely large documents like this.

**Comment by burnnat** [comment]
One other data point: most applications limit PDF page size at 200 inches, which *is* larger than our current max of 120 inches.

**Comment by alexgarciab** [comment]
Yes, I was talking about the maximum height. In my case, I need larger documents because I work with software specification where I need to create documents with images and text and I prefer to read it everything without page breaks and empty spaces due to images going to the next page.

**Comment by cyruslk** [comment]
Hey nice package. Quick question: what happens when you exceed the page height you entered? It would be also great to add a feature to adjust the page size to the actual document (I have a doc of 15 pages let's say, so that I don't have to do the 15 x 11inches math, even if its not that complicated!).
