### ISSUE TITLE
Page Sizer make my Google Docs very SLOW!

### ISSUE THREAD

**Issue by aspargus22** [burnnat/custom-page-size#4]
Hello guys,

I installed the add-on "Page Sizer" today on my Google Docs. 
I also followed the instructions to use the inspector to change the value of the height to "9999" for some docs. But after this, my Google Docs became extremally slow! 

I managed to uninstall the add-on "Page Sizer" after a while. However, my Google Docs is still very very slow.

Could you help me, please?

Thanks in advance

**Alex**
paraoalex@gmail.com
youtoalex@gmail.com

MacBook Air (13-inch, Mid 2012) / 1.8 GHz Intel Core i5 / 4 GB 1600 MHz DDR3 / Intel HD Graphics 4000 1536 MB // Chrome Versión 70.0.3538.77 (Build oficial) (64 bits)

**Comment by burnnat** [comment]
Hi Alex, thanks for reporting this. Unfortunately, the maximum page height was specifically requested by Google since their code is not tested to handle documents of unlimited size, so I can't offer any real assistance for pages sizes outside the supported bounds since the issue would lie in Google's codebase rather than the addon's. For that reason, uninstalling the addon will not help because the size of the document has already been changed and the slowness is being driven by the core Google Docs application. Resizing the page back to a smaller size, either using Page Sizer or the built-in Docs [page setup](https://support.google.com/docs/answer/143346?hl=en&ref_topic=9045928) should make the document responsive again.

Alternatively, since you may already be familiar with the Chrome DevTools inspector, you can use it to [capture and analyze performance data for that page](https://developers.google.com/web/tools/chrome-devtools/evaluate-performance/) which might provide clues to a workaround if there is one. But again, I won't be able to help diagnose the performance data since it is well outside the range supported by the addon. Hacking the page size form through the inspector is clever, but very much "at your own risk" because outside of the supported limits [there be dragons](https://en.wikipedia.org/wiki/Here_be_dragons)... 🐉 😉

**Comment by burnnat** [comment]
Closing as this is unresolvable from our end.
